version: "1.0"
info:
  model: int-scaffold
packages:
- name: Test4Project
  gitServerName: https://github.com/
  gitUrl: https://github.com/y509522/Test4Project
  gitUsername: y509522
  gitBranch: main
